In [1]:
#Data Analysis - Zomato mumbai - Dataset

In [2]:
#1.Importing Libraries
import pandas as pd  # Data manipulation
import numpy as np   # Numerical operations
import matplotlib.pyplot as plt  # Static plotting
import seaborn as sns  # Statistical visualization
import plotly.express as px  # Interactive charts
import plotly.io as pio  # Plotly settings

pio.renderers.default = "browser"    # opens in browser

In [3]:
#2.Importing the Dataset
raw_df=pd.read_csv('Zomato_Mumbai_Dataset.csv',delimiter='|') #Variable name — stores the dataset ("raw" = unprocessed data, "df" = DataFrame)

In [4]:
raw_df.head() #raw_df - The DataFrame we just loaded
#.head()Method that displays the first 5 rows of the DataFrame for a quick preview

,NAME,PRICE,CUSINE_CATEGORY,CITY,REGION,URL,PAGE NO,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES
0,Hitchki,1200,"Modern Indian,North Indian,Chinese,Momos,Birya...",Mumbai,First International Financial Centre-- Bandra ...,https://www.zomato.com/mumbai/hitchki-bandra-k...,1,Casual Dining,12noon to 130am(Mon-Sun),Excellent,4.9,3529
1,Baba Falooda,400,"Desserts,Ice Cream,Beverages",Mumbai,Mahim,https://www.zomato.com/mumbai/baba-falooda-mah...,1,Dessert Parlor,2pm to 1am(Mon-Sun),Very Good,4.4,1723
2,Chin Chin Chu,1800,"Asian,Chinese",Mumbai,Juhu,https://www.zomato.com/mumbai/chin-chin-chu-ju...,1,Casual Dining,12noon to 1am(Mon-Sun),Very Good,4.2,337
3,Butterfly High,1000,Modern Indian,Mumbai,Bandra Kurla Complex,https://www.zomato.com/mumbai/butterfly-high-b...,1,Bar,12noon to 130am(Mon-Sun),Very Good,4.3,1200
4,BKC DIVE,1200,"North Indian,Chinese,Continental",Mumbai,Bandra Kurla Complex,https://www.zomato.com/mumbai/bkc-dive-bandra-...,1,Bar,1130am to 1am(Mon-Sun),Veľmi dobré,4.4,5995

In [5]:
#3.Getting basic information about the dataset
raw_df.shape #raw_df - The DataFrame containing the Zomato Mumbai dataset
#.shape - A property (not a function) that returns the number of rows and columns as (rows, columns)

#raw_df.shape - tells you how big your dataset is — total rows (restaurants) × total columns (features)

(15081, 12)

In [6]:
raw_df.info() #raw_df - The DataFrame containing the Zomato Mumbai dataset
#.info() - A method that prints a summary of the DataFrame — column names, data types, non-null counts, and memory usage

#raw_df.info() - gives a quick health check of your dataset — size, column types, and missing value counts

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15081 entries, 0 to 15080
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   NAME             15081 non-null  object
 1   PRICE            15080 non-null  object
 2   CUSINE_CATEGORY  15079 non-null  object
 3   CITY             15080 non-null  object
 4   REGION           15080 non-null  object
 5   URL              15080 non-null  object
 6   PAGE NO          15080 non-null  object
 7   CUSINE TYPE      15080 non-null  object
 8   TIMING           15015 non-null  object
 9   RATING_TYPE      14070 non-null  object
 10  RATING           15080 non-null  object
 11  VOTES            15080 non-null  object
dtypes: object(12)
memory usage: 1.4+ MB

In [7]:
raw_df.describe() #raw_df - The Zomato Mumbai DataFrame
#.describe() - Method that gives statistical summary of columns

#raw_df.describe() - gives a statistical snapshot of the dataset — for text columns it shows frequency and unique value counts

,NAME,PRICE,CUSINE_CATEGORY,CITY,REGION,URL,PAGE NO,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES
count,15081,15080,15079,15080,15080,15080,15080,15080,15015,14070,15080,15080
unique,12720,67,3183,2,241,13823,944,23,2551,31,35,1124
top,NAME,400,CUSINE_CATEGORY,Mumbai,REGION,URL,PAGE NO,Quick Bites,11am to 11pm(Mon-Sun),Average,-,-
freq,942,2042,942,14138,942,942,942,5262,1192,5112,2360,2360

In [8]:
#4.Cleaning the dataset
#A.Removing the redundunt rows of data

#Checking redundunt rows of data
wrong_data = raw_df["PAGE NO"] =="PAGE NO"
raw_df[wrong_data]

#1.wrong_data - A variable that stores a True/False (boolean) mask for each row
#2.raw_df["PAGE NO"] - Selects the "PAGE NO" column from the DataFrame
#3.== "PAGE NO" - Checks if the column value equals the text "PAGE NO" — returns True if yes, False if no
#4.raw_df[wrong_data] - Filters and displays only the rows where wrong_data is True

#raw_df[wrong_data] - Identifies repeated header rows mistakenly entered as data, so they can be removed during cleaning

,NAME,PRICE,CUSINE_CATEGORY,CITY,REGION,URL,PAGE NO,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES
15,NAME,PRICE,CUSINE_CATEGORY,CITY,REGION,URL,PAGE NO,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES
31,NAME,PRICE,CUSINE_CATEGORY,CITY,REGION,URL,PAGE NO,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES
47,NAME,PRICE,CUSINE_CATEGORY,CITY,REGION,URL,PAGE NO,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES
63,NAME,PRICE,CUSINE_CATEGORY,CITY,REGION,URL,PAGE NO,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES
79,NAME,PRICE,CUSINE_CATEGORY,CITY,REGION,URL,PAGE NO,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES
...,...,...,...,...,...,...,...,...,...,...,...,...
15000,NAME,PRICE,CUSINE_CATEGORY,CITY,REGION,URL,PAGE NO,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES
15016,NAME,PRICE,CUSINE_CATEGORY,CITY,REGION,URL,PAGE NO,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES
15032,NAME,PRICE,CUSINE_CATEGORY,CITY,REGION,URL,PAGE NO,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES
15048,NAME,PRICE,CUSINE_CATEGORY,CITY,REGION,URL,PAGE NO,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES
15064,NAME,PRICE,CUSINE_CATEGORY,CITY,REGION,URL,PAGE NO,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES

In [9]:
#Performing Negation of the wrong dataset and then storing the correct data back in the raw_df DataFrame
#This permanently remove the wrong data from the original dataframe

raw_df=raw_df[~wrong_data] 

#1.raw_df - The DataFrame being updated (overwritten with clean data)
#2.= Assignment — stores the filtered result back into raw_df
#3.raw_df[...] - Filters rows from the DataFrame
#4.~ Negation operator — flips True → False and False → True
#5.wrong_data - The boolean mask where True = junk rows (PAGE NO header rows)
#6.~wrong_data - Now True = good rows, False = junk rows


#~wrong_data - flips the filter to keep only valid rows, permanently removing junk header rows from the DataFrame

In [10]:
#Dropping columns which are not required for further analysis
raw_df.drop(['URL','PAGE NO','CITY'],axis=1,inplace=True)

#1.raw_df - The Zomato Mumbai DataFrame
#2..drop() - Method that removes specified rows or columns
#3.['URL', 'PAGE NO', 'CITY'] - List of column names to be deleted
#4.axis=1 - Tells pandas to drop columns (axis=1) not rows (axis=0)
#5.inplace=True - Permanently modifies raw_df without needing reassignment

#Permanently removes 3 unnecessary columns (URL, PAGE NO, CITY) to keep only the columns useful for analysis

In [11]:
raw_df.head() 
#raw_df.head() - here acts as a quick sanity check to confirm the dataset is clean and ready for analysis

,NAME,PRICE,CUSINE_CATEGORY,REGION,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES
0,Hitchki,1200,"Modern Indian,North Indian,Chinese,Momos,Birya...",First International Financial Centre-- Bandra ...,Casual Dining,12noon to 130am(Mon-Sun),Excellent,4.9,3529
1,Baba Falooda,400,"Desserts,Ice Cream,Beverages",Mahim,Dessert Parlor,2pm to 1am(Mon-Sun),Very Good,4.4,1723
2,Chin Chin Chu,1800,"Asian,Chinese",Juhu,Casual Dining,12noon to 1am(Mon-Sun),Very Good,4.2,337
3,Butterfly High,1000,Modern Indian,Bandra Kurla Complex,Bar,12noon to 130am(Mon-Sun),Very Good,4.3,1200
4,BKC DIVE,1200,"North Indian,Chinese,Continental",Bandra Kurla Complex,Bar,1130am to 1am(Mon-Sun),Veľmi dobré,4.4,5995

In [12]:
#B.Removing the null records
#Checking for Null records
raw_df.isnull().sum()

#1.raw_df - The cleaned Zomato Mumbai DataFrame
#2..isnull() - Returns a True/False DataFrame — True where value is missing (NaN), False where value exists
#3..sum() - Counts the number of True values per column (since True=1, False=0)

#isnull().sum() - counts missing values per column to identify which columns need cleaning

NAME                  0
PRICE                 1
CUSINE_CATEGORY       2
REGION                1
CUSINE TYPE           1
TIMING               66
RATING_TYPE        1011
RATING                1
VOTES                 1
dtype: int64

In [13]:
#Checking for a null row
raw_df[raw_df['PRICE'].isnull()]

#1.raw_df['PRICE'] - Selects the PRICE column from the DataFrame
#2..isnull() - Returns True for rows where PRICE is missing (NaN), False where it has a value
#3.raw_df[...] - Filters and displays only the rows where PRICE is null

#Displays all restaurant rows where the PRICE value is missing, so we can decide how to handle them

,NAME,PRICE,CUSINE_CATEGORY,REGION,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES
15080,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
#Droping the above row from the dataset
raw_df = raw_df.drop(labels=15080, axis=0)

#1.raw_df - The Zomato Mumbai DataFrame being updated
#2..drop() - Method that removes a specific row or column
#3.labels=15080 - The index number of the row to be deleted (row at index 15080)
#4.axis=0 - Tells pandas to drop a row (axis=0) not a column (axis=1)
#5.raw_df = Reassigns the result back — since inplace=True is not used here

#Removes the specific row (index 15080) that had a missing PRICE value from the DataFrame

In [15]:
#Replacing the other null records with NA
raw_df.fillna('NA', inplace=True)

#1.raw_df - The Zomato Mumbai DataFrame
#2..fillna() - Method that fills missing (NaN) values with a specified value
#3.'NA' - The replacement value — fills all NaN cells with the text "NA"
#4.inplace=True - Permanently modifies raw_df without needing reassignment

#Replaces all remaining NaN missing values with the text "NA" to ensure the DataFrame has no empty cells

In [16]:
#Confirming all the null records are correct
raw_df.isnull().sum()

#raw_df.isnull().sum() - Confirm no nulls left

#Final confirmation check to verify that all missing values have been successfully removed or filled

NAME               0
PRICE              0
CUSINE_CATEGORY    0
REGION             0
CUSINE TYPE        0
TIMING             0
RATING_TYPE        0
RATING             0
VOTES              0
dtype: int64

In [17]:
#C.Converting the dataTypes of numerical columns to numeric dataype
#Checking for text values in the column before converting it to numeric datatype
raw_df['RATING'].value_counts()

#1.raw_df['RATING'] - Selects the RATING column from the DataFrame
#2..value_counts() - Counts how many times each unique value appears in the column, sorted by frequency

#Shows how many restaurants have each rating value — helps identify valid ratings vs dirty values needing further cleaning

RATING
-          2360
3.5        1094
3.4        1036
3.6         960
NEW         953
3.3         926
3.7         917
3.2         801
3.8         782
3.1         734
3.0         622
3.9         596
2.9         409
4.0         408
2.8         309
4.1         298
4.2         199
2.7         170
4.3         148
4.4          99
2.6          77
Opening      57
4.5          46
2.5          39
4.6          32
2.4          26
4.7          13
2.3          10
2.1           5
2.2           4
4.8           4
4.9           2
1.8           1
2.0           1
Name: count, dtype: int64

In [18]:
#Replacing the text values with '0'
raw_df['RATING'].replace(to_replace=['-','NEW','Opening'], value='0', inplace=True)

#1.raw_df['RATING'] - Selects the RATING column from the DataFrame
#2..replace() - Method that substitutes specified values with a new value
#3.to_replace=['-', 'NEW', 'Opening'] - List of invalid/placeholder values to be replaced
#4.value='0' - The replacement value — all three are replaced with '0'
#5.inplace=True - Permanently modifies the column without reassignment

#Replaces all non-numeric invalid rating values (-, NEW, Opening) with '0' to prepare the RATING column for numerical analysis

C:\Users\bkann\AppData\Local\Temp\ipykernel_7172\801560764.py:2: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.

In [19]:
#Checking for text values in the column before converting it to numeric datatype
raw_df['VOTES'].value_counts()

#1.raw_df['VOTES'] - Selects the VOTES column from the DataFrame
#2..value_counts() - Counts how many times each unique value appears, sorted by frequency

#Inspects all unique values in VOTES column to spot any text/invalid entries before safely converting it to a numeric datatype

VOTES
-       2360
NEW      953
4        364
5        320
6        288
        ...
1029       1
7350       1
964        1
585        1
1249       1
Name: count, Length: 1123, dtype: int64

In [20]:
#Replacing the text values with '0'
raw_df['VOTES'].replace(to_replace=['-','NEW','Opening'], value='0', inplace=True)

#1.raw_df['VOTES'] - Selects the VOTES column from the DataFrame
#2..replace() - Method that substitutes specified values with a new value
#3.to_replace=['-', 'NEW', 'Opening'] - List of invalid text values to be replaced
#4.value='0' - Replaces all three invalid values with '0'
#5.inplace=True - Permanently modifies the column without reassignment

#Replaces all non-numeric invalid values in VOTES column with '0' so it can be safely converted to a numeric datatype

C:\Users\bkann\AppData\Local\Temp\ipykernel_7172\3251459983.py:2: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.

In [21]:
#Changing Data Type of the numerical columns
raw_df['PRICE'] = raw_df['PRICE'].astype('int64')
raw_df['RATING'] = raw_df['RATING'].astype('float64')
raw_df['VOTES'] = raw_df['VOTES'].astype('int64')

#Word/Term          Definition

#raw_df['PRICE']  → Selects the PRICE column
#raw_df['RATING'] → Selects the RATING column
#raw_df['VOTES']  → Selects the VOTES column
#.astype()        → Method that converts a column to a specified data type
#'int64'          → Integer type — whole numbers (e.g. 1000, 250)
#'float64'        → Decimal type — numbers with decimals (e.g. 4.2, 3.8)
#=                → Reassigns the converted column back

#Converts PRICE, RATING, and VOTES from text (object) to proper numeric datatypes so mathematical operations can be performed.

In [22]:
raw_df.info()

#Word/Term     Definition

#raw_df      → Zomato Mumbai DataFrame
#.info()     → Prints summary of the DataFrame — column names, data types, non-null counts, and memory usage

#Used here to confirm PRICE, RATING, and VOTES are successfully converted to int64 and float64 numeric datatypes.

<class 'pandas.core.frame.DataFrame'>
Index: 14138 entries, 0 to 15079
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   NAME             14138 non-null  object
 1   PRICE            14138 non-null  int64
 2   CUSINE_CATEGORY  14138 non-null  object
 3   REGION           14138 non-null  object
 4   CUSINE TYPE      14138 non-null  object
 5   TIMING           14138 non-null  object
 6   RATING_TYPE      14138 non-null  object
 7   RATING           14138 non-null  float64
 8   VOTES            14138 non-null  int64
dtypes: float64(1), int64(2), object(6)
memory usage: 1.1+ MB

In [23]:
#D.Working with 'Timing' column

In [24]:
raw_df['TIMING'].value_counts()

#Word/Term              Definition

#raw_df['TIMING']     → Selects the TIMING column from the DataFrame
#.value_counts()      → Counts how many times each unique value appears, sorted by frequency

#Inspects all unique timing values in the TIMING column to spot any invalid or inconsistent entries before cleaning.

TIMING
11am to 11pm(Mon-Sun)                              1192
11am to 12midnight(Mon-Sun)                         632
12noon to 12midnight(Mon-Sun)                       467
11am to 1130pm(Mon-Sun)                             309
10am to 10pm(Mon-Sun)                               267
                                                   ...
1130am to 4pm,630pm to 1230AM...                      1
12midnight to 5am,12noon to 12midnight(Mon-Sun)       1
12midnight to 1230AM,12noon to 4pm,7pm to ...         1
12noon to 330pm,630pm to 12midnight...                1
8am to 11pm,12midnight to 115am(Mon-Sun)              1
Name: count, Length: 2551, dtype: int64

In [25]:
#Splitting the column and storing it in temp_df dataframe
temp_df = raw_df['TIMING'].str.split("(", n = 1, expand = True)
temp_df

#Word/Term              Definition

#temp_df              → New temporary DataFrame to store the split result
#raw_df['TIMING']     → Selects the TIMING column from the DataFrame
#.str                 → Accessor to apply string methods on a column
#.split("(")          → Splits each value at the "(" character
#n = 1                → Split only once (maximum 1 split per value)
#expand = True        → Expands the split result into separate columns (0 and 1)
#temp_df              → Displays the resulting temporary DataFrame

#Splits the TIMING column at "(" into two parts — the time text (col 0) and the extra info in brackets (col 1),stored in a new temp_df for further processing.

                                     0                                 1
0                      12noon to 130am                          Mon-Sun)
1                           2pm to 1am                          Mon-Sun)
2                        12noon to 1am                          Mon-Sun)
3                      12noon to 130am                          Mon-Sun)
4                        1130am to 1am                          Mon-Sun)
...                                ...                               ...
15075  8am to 11pm,12midnight to 115am                          Mon-Sun)
15076                    11am to 230am                          Mon-Sun)
15077                     11am to 11pm  Mon,Tue,Wed,Thu,Sun),11am to ...
15078                    9am to 1230AM                          Mon-Sun)
15079       12noon to 330pm,7pm to 1am                          Mon-Sun)

[14138 rows x 2 columns]

In [26]:
#Assigning the columns back to the raw_df dataframe
raw_df['TIMING'] = temp_df[0]
raw_df['DAYS_OPEN'] = temp_df[1]
raw_df.head()

#Word/Term                Definition

#raw_df['TIMING']       → Selects/updates the TIMING column in raw_df
#raw_df['DAYS_OPEN']    → Creates a new column DAYS_OPEN in raw_df
#temp_df[0]             → Column 0 of temp_df — contains the time part
                         #(e.g. "11AM - 11PM")
#temp_df[1]             → Column 1 of temp_df — contains the days part
                         #(e.g. "Mon-Sun")
#=                      → Assigns the temp_df columns back to raw_df
#raw_df.head()          → Previews first 5 rows to verify the changes

#Assigns the split results back to raw_df — TIMING gets the clean time values and a new DAYS_OPEN column is created from the days/bracket part of the original TIMING column.

,NAME,PRICE,CUSINE_CATEGORY,REGION,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES,DAYS_OPEN
0,Hitchki,1200,"Modern Indian,North Indian,Chinese,Momos,Birya...",First International Financial Centre-- Bandra ...,Casual Dining,12noon to 130am,Excellent,4.9,3529,Mon-Sun)
1,Baba Falooda,400,"Desserts,Ice Cream,Beverages",Mahim,Dessert Parlor,2pm to 1am,Very Good,4.4,1723,Mon-Sun)
2,Chin Chin Chu,1800,"Asian,Chinese",Juhu,Casual Dining,12noon to 1am,Very Good,4.2,337,Mon-Sun)
3,Butterfly High,1000,Modern Indian,Bandra Kurla Complex,Bar,12noon to 130am,Very Good,4.3,1200,Mon-Sun)
4,BKC DIVE,1200,"North Indian,Chinese,Continental",Bandra Kurla Complex,Bar,1130am to 1am,Veľmi dobré,4.4,5995,Mon-Sun)

In [27]:
#Removing the bracket character from Days column
raw_df['DAYS_OPEN'] = raw_df['DAYS_OPEN'].str.replace('\)','',regex=True)
raw_df.head()

#Word/Term                Definition

#raw_df['DAYS_OPEN']    → Selects the DAYS_OPEN column from raw_df
#.str                   → Accessor to apply string methods on the column
#.replace('\)', '')     → '\)' → escaped regex for literal ")" character
                         #''   → replaces it with empty string (removes it)
#regex=True             → Treats '\)' as a regex escaped pattern
#=                      → Reassigns the cleaned result back to DAYS_OPEN
#raw_df.head()          → Previews first 5 rows to verify the changes

#Removes the closing bracket ")" from DAYS_OPEN column using escaped regex '\)' so pandas treats it as a plain character(e.g. "Mon-Sun)" → "Mon-Sun").

,NAME,PRICE,CUSINE_CATEGORY,REGION,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES,DAYS_OPEN
0,Hitchki,1200,"Modern Indian,North Indian,Chinese,Momos,Birya...",First International Financial Centre-- Bandra ...,Casual Dining,12noon to 130am,Excellent,4.9,3529,Mon-Sun
1,Baba Falooda,400,"Desserts,Ice Cream,Beverages",Mahim,Dessert Parlor,2pm to 1am,Very Good,4.4,1723,Mon-Sun
2,Chin Chin Chu,1800,"Asian,Chinese",Juhu,Casual Dining,12noon to 1am,Very Good,4.2,337,Mon-Sun
3,Butterfly High,1000,Modern Indian,Bandra Kurla Complex,Bar,12noon to 130am,Very Good,4.3,1200,Mon-Sun
4,BKC DIVE,1200,"North Indian,Chinese,Continental",Bandra Kurla Complex,Bar,1130am to 1am,Veľmi dobré,4.4,5995,Mon-Sun

In [28]:
#Checking for Null records in DAYS_OPEN column
raw_df.isnull().sum()

#Word/Term        Definition

#raw_df         → Zomato Mumbai DataFrame
#.isnull()      → Returns True where value is missing (NaN),
                 #False where value exists
#.sum()         → Counts the number of True values per column
                 #(True=1, False=0)

#Checks if the newly created DAYS_OPEN column (or any othercolumn) has introduced any null values after the TIMING column split operation.

NAME                 0
PRICE                0
CUSINE_CATEGORY      0
REGION               0
CUSINE TYPE          0
TIMING               0
RATING_TYPE          0
RATING               0
VOTES                0
DAYS_OPEN          160
dtype: int64

In [29]:
#Replacing the Null values with 'NA'
raw_df.fillna('NA', inplace=True)

#Word/Term        Definition

#raw_df         → Zomato Mumbai DataFrame
#.fillna()      → Method that fills all missing (NaN) values
                 #with a specified replacement value
#'NA'           → Replacement text filled in place of NaN
#inplace=True   → Permanently modifies raw_df without reassignment

#Fills any new null values introduced in DAYS_OPEN (or other columns) after the TIMING split operation with 'NA', ensuring no empty cells remain in the DataFrame.

In [30]:
#Checking info of all the columns
raw_df.info()

#Word/Term      Definition

#raw_df       → Zomato Mumbai DataFrame
#.info()      → Prints summary of the DataFrame — column names,
               #data types, non-null counts, and memory usage

#Final check to confirm all columns have correct datatypes, no null values remain, and the new DAYS_OPEN column is successfully added to the DataFrame.

<class 'pandas.core.frame.DataFrame'>
Index: 14138 entries, 0 to 15079
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   NAME             14138 non-null  object
 1   PRICE            14138 non-null  int64
 2   CUSINE_CATEGORY  14138 non-null  object
 3   REGION           14138 non-null  object
 4   CUSINE TYPE      14138 non-null  object
 5   TIMING           14138 non-null  object
 6   RATING_TYPE      14138 non-null  object
 7   RATING           14138 non-null  float64
 8   VOTES            14138 non-null  int64
 9   DAYS_OPEN        14138 non-null  object
dtypes: float64(1), int64(2), object(7)
memory usage: 1.2+ MB

In [31]:
#E.Removing the restaurant records whose Rating or Votes is 0
#Finding those restaurant whose has 0 Rating or Votes
useless_data = (raw_df['RATING'] == 0.0) | (raw_df['VOTES'] == 0)
raw_df[useless_data]

#Word/Term                    Definition

#useless_data               → Variable storing a True/False boolean mask
#raw_df['RATING'] == 0.0    → Returns True where RATING value is 0.0
#raw_df['VOTES'] == 0       → Returns True where VOTES value is 0
#|                          → OR operator — True if either condition is True
#(  )                       → Brackets group each condition separately
#useless_data               → Combined mask: True = restaurant has 0 Rating
                             #OR 0 Votes
#raw_df[useless_data]       → Filters and displays only those rows where
                             #useless_data is True

#Identifies restaurants with 0 Rating OR 0 Votes — these are newly listed or inactive restaurants with no useful data, so they need to be removed from the analysis.

,NAME,PRICE,CUSINE_CATEGORY,REGION,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES,DAYS_OPEN
32,Hotel Annapoorna Refreshments,400,"Maharashtrian,Mughlai,Chinese",Ghansoli,Quick Bites,1030am to 1230AM,Not rated,0.0,0,Mon-Sun
34,Biryani 9,600,"Biryani,North Indian",Near Andheri East Station,none,11am to 3am,NA,0.0,0,Mon-Sun
36,D Fusion Flavours,350,Chinese,Goregaon East,none,"12noon to 330pm,7pm to 3am",NA,0.0,0,Mon-Sun
39,Nation Tadka,400,"North Indian,South Indian,Chinese,Fast Food",Worli,none,12noon to 1230AM,Not rated,0.0,0,Mon-Sun
83,Link Way Restaurant,500,"North Indian,Chinese",Jogeshwari,Quick Bites,"12noon to 4pm,8pm to 1am",Not rated,0.0,0,Mon-Sun
...,...,...,...,...,...,...,...,...,...,...
14998,Foodies House,0,Chinese,Goregaon East,none,12noon to 4am,NA,0.0,0,Mon-Sun
14999,Khansama,0,Biryani,Lower Parel,none,12noon to 3am,NA,0.0,0,Mon-Sun
15010,Earth Cafe @ Waterfield,800,"Cafe,Healthy Food,Italian,Pizza,Beverages",Linking Road-- Bandra West,Café,10am to 10pm,NA,0.0,0,"Mon-Thu,10am to 11pm(Fri-Sun"
15023,How About Some Cream,200,Beverages,Mumbai Central,Beverage Shop,12noon to 3am,NA,0.0,0,Mon-Sun
15046,Food And Taste Theory,800,"Continental,Italian",Phoenix Marketcity-- Kurla,Casual Dining,9am to 12midnight,NA,0.0,0,"Mon-Fri,9am to 1230AM(Sat-Sun"

In [32]:
#Performing Negation of the useless dataset and then storing the correct data back in the raw_df DataFrame
#This permanently removes the wrong data from the original dataframe
raw_df = raw_df[~useless_data]

#Word/Term              Definition

#raw_df               → Zomato Mumbai DataFrame being updated
#=                    → Reassigns the filtered result back to raw_df
#raw_df[...]          → Filters rows from the DataFrame
#~                    → Negation operator — flips True→False, False→True
#useless_data         → Boolean mask where True = 0 Rating OR 0 Votes rows
#~useless_data        → Now True = valid restaurants, False = useless rows

#Permanently removes all restaurants with 0 Rating OR 0 Votes by keeping only the rows where ~useless_data is True, leaving only meaningful restaurant records for analysis.

In [33]:
#F.Working on 'RATING_TYPE' Column
#Checking the unique values in the column
raw_df['RATING_TYPE'].value_counts()

#Word/Term                  Definition

#raw_df['RATING_TYPE']    → Selects the RATING_TYPE column from raw_df
#.value_counts()          → Counts how many times each unique value
                           #appears, sorted by highest frequency first

#Inspects all unique rating type categories in the RATING_TYPE column to understand the distribution and spot any inconsistent or invalid entries before cleaning.

RATING_TYPE
Average          5111
Good             4330
Very Good        1137
Excellent          95
Poor               47
Veľmi dobré         6
Skvělá volba        4
Dobrze              4
Bardzo dobrze       3
Ortalama            2
Bueno               2
İyi                 2
Buono               2
Dobré               2
Bom                 2
Priemer             2
Průměr              2
Muito Bom           2
Promedio            2
Muy Bueno           1
Sangat Baik         1
Média               1
Biasa               1
Skvělé              1
Baik                1
Çok iyi             1
Excelente           1
Velmi dobré         1
Media               1
Name: count, dtype: int64

In [34]:
#Translating the texts into proper English text
raw_df['RATING_TYPE'].replace(to_replace='Excelente' , value='Excellent', inplace=True)
raw_df['RATING_TYPE'].replace(to_replace=['Veľmi dobré','Bardzo dobrze','Muy Bueno','Velmi dobré'] , value='Very Good',)
raw_df['RATING_TYPE'].replace(to_replace=['Skvělá volba','Dobrze','Bueno','Buono','Dobré','Bom','Skvělé'] , value='Good',)
raw_df['RATING_TYPE'].replace(to_replace=['Priemer','Média','Çok iyi'] , value='Average', inplace=True)
raw_df['RATING_TYPE'].replace(to_replace=['Průměr','Promedio','Ortalama','Muito Bom','İyi'] , value='Poor', inplace=True)
raw_df['RATING_TYPE'].replace(to_replace=['Baik','Biasa','Media','Sangat Baik'] , value='Very Poor', inplace=True)

#Word/Term                        Definition

#raw_df['RATING_TYPE']          → Selects the RATING_TYPE column
#.replace()                     → Substitutes specified values with a new value
#to_replace=                    → List of foreign language words to be replaced
#value=                         → The English translation to replace them with
#inplace=True                   → Permanently modifies the column without reassignment

C:\Users\bkann\AppData\Local\Temp\ipykernel_7172\2899319448.py:2: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.



C:\Users\bkann\AppData\Local\Temp\ipykernel_7172\2899319448.py:5: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.

In [35]:
#Checking all the values are correctly mapped
raw_df['RATING_TYPE'].value_counts()

#Word/Term                  Definition

#raw_df['RATING_TYPE']    → Selects the RATING_TYPE column from raw_df
#.value_counts()          → Counts how many times each unique value
                           #appears, sorted by highest frequency first

#Verification step — confirms all foreign language values are correctly translated into standard English categories(Excellent, Very Good, Good, Average, Poor, Very Poor).

RATING_TYPE
Average          5115
Good             4330
Very Good        1137
Excellent          96
Poor               57
Veľmi dobré         6
Dobrze              4
Very Poor           4
Skvělá volba        4
Bardzo dobrze       3
Bom                 2
Buono               2
Bueno               2
Dobré               2
Velmi dobré         1
Skvělé              1
Muy Bueno           1
Name: count, dtype: int64

In [36]:
#G.Working on 'REGION' Column
raw_df['REGION'].value_counts()

#Word/Term              Definition

#raw_df['REGION']     → Selects the REGION column from raw_df
#.value_counts()      → Counts how many times each unique value
                       #appears, sorted by highest frequency first

#Inspects all unique Mumbai regions/areas in the REGION column to understand restaurant distribution across different localities and spot any inconsistent entries before cleaning.

REGION
Mira Road                            405
Malad West                           308
Chembur                              277
Kharghar                             268
Borivali West                        264
                                    ...
Hotel Emerald-- Juhu                   1
Trident-- Bandra Kurla Complex         1
Sea Princess-- Juhu                    1
Aureole Hotel-- Andheri East           1
Hotel Satkar Residency-- Majiwada      1
Name: count, Length: 237, dtype: int64

In [37]:
#Removing the irrelevant text from the Region column
raw_df['REGION'] = raw_df['REGION'].str.replace('[a-zA-Z].+-- ','',regex=True)

#Word/Term              Definition

#raw_df['REGION']     → Selects the REGION column from raw_df
#.str                 → Accessor to apply string methods on the column
#.replace()           → Substitutes matched pattern with a new value
#'[a-zA-Z].+-- '     → Regex pattern:
#   [a-zA-Z]         →   Matches any letter (upper or lowercase)
#   .+               →   Followed by one or more of any character
#   --               →   Followed by literal "--"
#   ' '              →   Followed by a space
#''                   → Replaces matched text with empty string (removes it)
#regex=True           → Treats the pattern as a regex expression
#=                    → Reassigns the cleaned result back to REGION

#Removes irrelevant prefix text (e.g. "Restaurants in Mumbai -- ")from the REGION column, keeping only the clean locality/area name (e.g. "Bandra", "Andheri").

In [38]:
#Removing the West & East from the Region column
raw_df['REGION'] = raw_df['REGION'].str.replace(' West| west| East| east','',regex=True)

#Word/Term                    Definition

#raw_df['REGION']           → Selects the REGION column from raw_df
#.str                       → Accessor to apply string methods on the column
#.replace()                 → Substitutes matched pattern with a new value
#' West| west| East| east'  → Regex pattern:
#   ' West'                 →   Matches " West" (with space before)
#   | west                  →   OR " west" (lowercase)
#   | East                  →   OR " East"
#   | east                  →   OR " east" (lowercase)
#   |                       →   OR operator in regex
#''                         → Replaces all matched text with empty string
#regex=True                 → Treats the pattern as a regex expression
#=                          → Reassigns the cleaned result back to REGION

#Removes directional suffixes "West" and "East" (both upper and lowercase) from REGION values to standardize area names (e.g. "Andheri West" → "Andheri").

In [39]:
raw_df['REGION'].value_counts()

REGION
Thane                726
Mira Road            412
Andheri              409
Malad                378
Kandivali            377
                    ...
Flea Bazaar Café       3
Majiwada               3
Panvel                 2
CBD Belapur            1
Girgaon Chowpatty      1
Name: count, Length: 101, dtype: int64

In [40]:
#Replacing Small regions with Known region name
raw_df['REGION'] = raw_df['REGION'].str.replace(
    '4 Bungalows|7 Andheri|Azad Nagar|Near Andheri Station|Veera Desai Area',
    'Andheri',
    regex=True
)
raw_df['REGION'] = raw_df['REGION'].str.replace('Bandra Kurla Complex','Bandra',regex=True)
raw_df['REGION'] = raw_df['REGION'].str.replace('CBD-Belapur','CBD Belapur',regex=True)
raw_df['REGION'] = raw_df['REGION'].str.replace('Girgaon Chowpatty','Chowpatty',regex=True)
raw_df['REGION'] = raw_df['REGION'].str.replace('Dadar Shivaji Park','Dadar',regex=True)
raw_df['REGION'] = raw_df['REGION'].str.replace('Flea Bazaar Café|Kamala Mills Compound','Lower Parel',regex=True)
raw_df['REGION'] = raw_df['REGION'].str.replace('Runwal Green','Mulund',regex=True)
raw_df['REGION'] = raw_df['REGION'].str.replace('Mumbai CST Area','Mumbai Central',regex=True)
raw_df['REGION'] = raw_df['REGION'].str.replace('Kopar Khairane|Seawoods|Turbhe|Ulwe','Navi Mumbai',regex=True)
raw_df['REGION'] = raw_df['REGION'].str.replace('New Panvel|Old Panvel','Panvel',regex=True)
raw_df['REGION'] = raw_df['REGION'].str.replace('Kamothe','Sion',regex=True)
raw_df['REGION'] = raw_df['REGION'].str.replace('Ghodbunder Road|Majiwada','Thane',regex=True)

#Word/Term                Definition

#raw_df['REGION']       → Selects the REGION column from raw_df
#.str.replace()         → Finds and replaces text using a regex pattern
#pat (1st argument)     → The small/obscure region name(s) to find
#repl (2nd argument)    → The known parent region name to replace with
#|                      → OR operator — matches either value in regex
#regex=True             → Treats the pattern as a regex expression
#=                      → Reassigns cleaned result back to REGION

#Small Region → Known Region Mapping:

#'4 Bungalows|7 Andheri|Azad Nagar|
#Near Andheri Station|Veera Desai Area' → 'Andheri'
#'Bandra Kurla Complex'                  → 'Bandra'
#'CBD-Belapur'                           → 'CBD Belapur'
#'Girgaon Chowpatty'                     → 'Chowpatty'
#'Dadar Shivaji Park'                    → 'Dadar'
#'Flea Bazaar Café|Kamala Mills Compound'→ 'Lower Parel'
#'Runwal Green'                          → 'Mulund'
#'Mumbai CST Area'                       → 'Mumbai Central'
#'Kopar Khairane|Seawoods|Turbhe|Ulwe'  → 'Navi Mumbai'
#'New Panvel|Old Panvel'                 → 'Panvel'
#'Kamothe'                               → 'Sion'
#'Ghodbunder Road|Majiwada'              → 'Thane'

#Consolidates small/obscure locality names into their larger, well-known parent regions to standardize the REGION column for cleaner and more meaningful analysis.

In [41]:
#H.Removing Duplicate records
#Finding all the duplicate rows
raw_df[raw_df.duplicated()]

#Word/Term              Definition

#raw_df               → Zomato Mumbai DataFrame
#.duplicated()        → Returns True for rows that are exact duplicates
                       #of a previous row, False for unique rows
#raw_df[...]          → Filters and displays only the duplicate rows

#Finds and displays all duplicate rows in the DataFrame where every column value is identical to a previous row, so they can be removed to avoid skewed analysis.

,NAME,PRICE,CUSINE_CATEGORY,REGION,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES,DAYS_OPEN
4064,Sai Sannidhi Restaurant & Bar,1000,"North Indian,Konkan",Dahisar,Casual Dining,11am to 12midnight,Good,3.7,99,Mon-Sun
4068,Konkan Katta,400,"Seafood,Maharashtrian,Malwani",Mahakali,Quick Bites,"11am to 330pm,630pm to 1130pm",Good,3.5,181,Mon-Sun
4082,Usmaniya Hotel,600,Mughlai,Fort,Casual Dining,1030am to 1130pm,Average,3.2,8,Mon-Sun
4083,Gina's Cakes,450,Bakery,Dombivali,none,11am to 11pm,Good,3.5,49,Mon-Sun
4084,Konkanastha Lunch Home,400,"Seafood,Malwani",Chakala,Casual Dining,"12noon to 3pm,730pm to 1030pm",Good,3.5,44,Mon-Sun
...,...,...,...,...,...,...,...,...,...,...
14200,Mezbaan Family Restaurant,350,"Chinese,Mughlai",Mumbra,Dhaba,12noon to 1230AM,Average,2.8,97,Mon-Sun
14204,Jyoti Lunch Home,650,"Chinese,North Indian,Seafood,Mughlai",Mulund,Casual Dining,11am to 1230AM,Good,3.5,49,Mon-Sun
14253,On Toes,900,"Italian,North Indian,Chinese",Malad,Casual Dining,"12noon to 3pm,7pm to 1230AM",Good,3.6,76,Mon-Sun
14761,Frosty Farm,400,"Ice Cream,Desserts,Fast Food",Malad,Dessert Parlor,1pm to 1215AM,Good,3.6,120,Mon-Sun
14928,Shree Manu Sagar,300,"North Indian,Chinese,Indian",Ghansoli,Quick Bites,"1130am to 415pm,7pm to 1215AM",Average,3.3,51,Mon-Sun

In [42]:
#Dropping all the duplicate rows
raw_df = raw_df.drop_duplicates()

#Word/Term              Definition

#raw_df               → Zomato Mumbai DataFrame being updated
#=                    → Reassigns the cleaned result back to raw_df
#.drop_duplicates()   → Removes all duplicate rows, keeping only the
                       #first occurrence of each repeated row

#Permanently removes all duplicate rows from the DataFrame, keeping only unique restaurant records to ensure accurate and unbiased analysis.

In [43]:
#4.Copying the cleaned data into a new DataFrame
zomato_df = raw_df.copy()

#Word/Term        Definition

#zomato_df      → New DataFrame to store the fully cleaned data
#=              → Assigns the copied result to zomato_df
#raw_df         → The cleaned Zomato Mumbai DataFrame
#.copy()        → Creates an independent copy of raw_df —
                 #changes to zomato_df will NOT affect raw_df

#Copies the fully cleaned raw_df into a new DataFrame zomato_df so the original cleaned data is preserved safely while zomato_df is used for all further analysis.

In [44]:
zomato_df.head()

#Word/Term        Definition

#zomato_df      → The newly copied, cleaned DataFrame
#.head()        → Displays the first 5 rows of the DataFrame

#Quick preview of the final cleaned zomato_df to visually confirm all cleaning steps are correctly applied before moving on to analysis and visualization.

,NAME,PRICE,CUSINE_CATEGORY,REGION,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES,DAYS_OPEN
0,Hitchki,1200,"Modern Indian,North Indian,Chinese,Momos,Birya...",Bandra,Casual Dining,12noon to 130am,Excellent,4.9,3529,Mon-Sun
1,Baba Falooda,400,"Desserts,Ice Cream,Beverages",Mahim,Dessert Parlor,2pm to 1am,Very Good,4.4,1723,Mon-Sun
2,Chin Chin Chu,1800,"Asian,Chinese",Juhu,Casual Dining,12noon to 1am,Very Good,4.2,337,Mon-Sun
3,Butterfly High,1000,Modern Indian,Bandra,Bar,12noon to 130am,Very Good,4.3,1200,Mon-Sun
4,BKC DIVE,1200,"North Indian,Chinese,Continental",Bandra,Bar,1130am to 1am,Veľmi dobré,4.4,5995,Mon-Sun

In [45]:
#5.Performing Exploratory Data Analysis
#Q1) How many restaurants are in Mumbai for each type of cuisine?
fig = px.histogram(zomato_df, x='CUSINE TYPE', color='CUSINE TYPE',
title= 'No. of Restaurants by Cuisine Type',
labels={'CUSINE TYPE':'Cuisine Type'})
fig.show()

#Word/Term                        Definition

#fig                            → Variable storing the plotly figure object
#px                             → Alias for plotly.express library
#.histogram()                   → Creates a histogram (bar chart of frequencies)
#zomato_df                      → The cleaned Zomato Mumbai DataFrame
#x='CUSINE TYPE'                → X-axis shows the CUSINE TYPE column values
#color='CUSINE TYPE'            → Each cuisine type gets a different colour bar
#title=                         → Sets the chart title as
                                 #'No. of Restaurants by Cuisine Type'
#labels=                        → Renames axis label:
#{'CUSINE TYPE':'Cuisine Type'} → 'CUSINE TYPE' → displayed as 'Cuisine Type'
#fig.show()                     → Renders and displays the chart

#Creates a colour-coded histogram showing the count of restaurants for each cuisine type in Mumbai, helping identify the most and least popular cuisines.

In [46]:
!pip install --upgrade kaleido

Requirement already satisfied: kaleido in C:\Users\bkann\anaconda3\envs\aiml\Lib\site-packages (1.3.0)
Requirement already satisfied: choreographer>=1.3.0 in C:\Users\bkann\anaconda3\envs\aiml\Lib\site-packages (from kaleido) (1.3.0)
Requirement already satisfied: logistro>=1.0.8 in C:\Users\bkann\anaconda3\envs\aiml\Lib\site-packages (from kaleido) (2.0.1)
Requirement already satisfied: orjson>=3.10.15 in C:\Users\bkann\anaconda3\envs\aiml\Lib\site-packages (from kaleido) (3.11.9)
Requirement already satisfied: packaging in C:\Users\bkann\anaconda3\envs\aiml\Lib\site-packages (from kaleido) (26.0)
Requirement already satisfied: platformdirs>=4.3.6 in C:\Users\bkann\anaconda3\envs\aiml\Lib\site-packages (from choreographer>=1.3.0->kaleido) (4.10.0)
Requirement already satisfied: simplejson>=3.19.3 in C:\Users\bkann\anaconda3\envs\aiml\Lib\site-packages (from choreographer>=1.3.0->kaleido) (4.1.1)

In [47]:
!python --version

Python 3.13.9

In [53]:
#Q2) What is the percentage of restaurants by Rating Type in Mumbai?
rating_type_df = zomato_df['RATING_TYPE'].value_counts().reset_index()
rating_type_df.columns = ['RATING TYPE', 'COUNT OF RESTAURANTS']
rating_type_df

#Word/Term                         Definition

#rating_type_df                  → New DataFrame to store rating type, counts
#zomato_df['RATING_TYPE']        → Selects the RATING_TYPE column
#.value_counts()                 → Counts occurrences of each unique rating type
#.reset_index()                  → Converts the result into a DataFrame with
                                   #a new default index column
#rating_type_df.columns =        → Directly assigns new column names
#['RATING TYPE',
# 'COUNT OF RESTAURANTS']        → Renames columns to 'RATING TYPE' and
                                   #'COUNT OF RESTAURANTS' in correct order
#rating_type_df                  → Displays the final renamed DataFrame

#EDA Question Answered:
#Q2 → What is the percentage of restaurants by Rating Type in Mumbai?

#Fixed version — directly assigns column names instead of using .rename(), successfully creating a clean summary table with 'RATING TYPE' and 'COUNT OF RESTAURANTS' columns.

      RATING TYPE  COUNT OF RESTAURANTS
0         Average                  4983
1            Good                  4246
2       Very Good                  1134
3       Excellent                    96
4            Poor                    56
5     Veľmi dobré                     6
6          Dobrze                     4
7       Very Poor                     4
8    Skvělá volba                     4
9   Bardzo dobrze                     3
10            Bom                     2
11          Buono                     2
12          Bueno                     2
13          Dobré                     2
14    Velmi dobré                     1
15         Skvělé                     1
16      Muy Bueno                     1

In [55]:
fig = px.pie(rating_type_df, names='RATING TYPE', values='COUNT OF RESTAURANTS', 
             color='RATING TYPE', title='Percentage of Restaurants by Rating Type')
fig.update_traces(textposition='inside', textinfo='percent+label')
fig.show()

#Word/Term                          Definition

#fig                               → Variable storing the plotly figure object
#px.pie()                          → Creates a pie chart
#rating_type_df                    → DataFrame with Rating Type counts
#names='RATING TYPE'               → Each pie slice labelled by RATING TYPE
#values='COUNT OF RESTAURANTS'     → Slice size based on COUNT OF RESTAURANTS
#color='RATING TYPE'               → Each slice gets a different colour per rating type
#title=                            → Sets chart title as
#'Percentage of Restaurants
 #by Rating Type'
#fig.update_traces()               → Modifies the appearance of pie chart elements
#textposition='inside'             → Places text labels inside each pie slice
#textinfo='percent+label'          → Displays both percentage and rating type label
#fig.show()                        → Renders and displays the pie chart

#EDA Question Answered:
#Q2 → What is the percentage of restaurants by Rating Type in Mumbai?

#Pie chart successfully created — shows the percentage distribution of restaurants across different rating types, with labels and percentages displayed on each slice.

In [57]:
#Q3)Which are the Top 10 highest rated Seafood Restaurant in Mumbai?
seafood_df = zomato_df[zomato_df['CUSINE_CATEGORY'].str.contains('Seafood')]
seafood_df.sort_values(by='RATING',ascending=False).head(10)

#Word/Term                              Definition

#seafood_df                           → New DataFrame to store seafood restaurants
#zomato_df['CUSINE_CATEGORY']         → Selects the CUSINE_CATEGORY column
#.str                                 → Accessor to apply string methods
#.contains('Seafood')                 → Returns True for rows where the text
                                        #contains "Seafood", False otherwise
#zomato_df[...]                       → Filters and keeps only Seafood restaurant rows
#seafood_df.sort_values()             → Sorts the DataFrame by a specified column
#by='RATING'                          → Sorts based on the RATING column
#ascending=False                      → Sorts from highest to lowest rating
#.head(10)                            → Returns only the top 10 rows

#EDA Question Answered:
#Q3 → Which are the Top 10 highest-rated Seafood Restaurants in Mumbai?

#Filters all restaurants that serve Seafood, then sorts them by rating in descending order to display the top 10. The highest-rated seafood restaurants in Mumbai.

,NAME,PRICE,CUSINE_CATEGORY,REGION,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES,DAYS_OPEN
7104,Thangabali,1000,"Seafood,South Indian,Mangalorean,Andhra,Kerala",Khar,Bar,"12noon to 4pm,7pm to 3am",Excellent,4.7,564,Mon-Sun
76,Ceremonial Kitchen & Co,1000,"Seafood,Maharashtrian,North Indian,Chinese",Thane,Casual Dining,1130am to 1130pm,Excellent,4.6,350,Mon-Sun
13685,Maharashtra Lunch Home,600,"Maharashtrian,Malwani,Konkan,Seafood",Kharghar,Casual Dining,"11am to 345pm,7pm to 1145pm",Excellent,4.6,209,Mon-Sun
12433,Quarter Canteen,1100,"North Indian,Seafood,Chinese",Bandra,Casual Dining,"12noon to 330pm,7pm to 1am",Excellent,4.5,573,Mon-Sun
902,The Harbour Bay - SeaFood Kitchen & Bar,2400,"Seafood,Beverages",Bandra,Casual Dining,12noon to 1am,Excellent,4.5,100,Mon-Sun
884,Rajmanya- Seafood family restaurant,800,"Maharashtrian,Konkan,Seafood",Vashi,Casual Dining,11am to 11pm,Excellent,4.5,178,Mon-Sun
3380,Peco Peco,700,"Chinese,Seafood,Asian",Powai,none,"12noon to 330pm,7pm to 1230AM",Excellent,4.5,497,Mon-Sun
9954,Pi Bar and Kitchen,1600,"Continental,European,Italian,Seafood,Pizza,Des...",Andheri,Bar,"12noon to 6pm,7pm to 12midnight",Excellent,4.5,2068,Mon-Sun
903,Ferry Wharf,1500,"Seafood,Mangalorean",Bandra,Casual Dining,"11am to 330pm,7pm to 1230AM",Very Good,4.4,459,Mon-Sun
915,Monis Bar and Restaurant,1000,"North Indian,Chinese,Continental,Seafood,Bever...",Thane,Casual Dining,"1130am to 330pm,6pm to 1130pm",Very Good,4.4,662,Mon-Sun

In [59]:
#Q4)Which is the best Food Truck in Mumbai?
foodtruck_df = zomato_df[zomato_df['CUSINE TYPE'] == 'Food Truck']
foodtruck_df.sort_values(by='RATING',ascending=False).head(2)

#Word/Term                       Definition

#foodtruck_df                  → New DataFrame to store Food Truck restaurants
#zomato_df['CUSINE TYPE']      → Selects the CUSINE TYPE column
#== 'Food Truck'               → Returns True for rows where the value
                                 #exactly equals "Food Truck"
#zomato_df[...]                → Filters and keeps only Food Truck rows
#foodtruck_df.sort_values()    → Sorts the DataFrame by a specified column
#by='RATING'                   → Sorts based on the RATING column
#ascending=False               → Sorts from highest to lowest rating
#.head(2)                      → Returns only the top 2 rows

#EDA Question Answered:
#Q4 → Which is the best Food Truck in Mumbai?

#Filters all restaurants categorized as "Food Truck", then sorts them by rating in descending order to display the top 2 highest-rated food trucks in Mumbai.

,NAME,PRICE,CUSINE_CATEGORY,REGION,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES,DAYS_OPEN
262,Dumpling Delights,200,Momos,Matunga,Food Truck,430pm to 930pm,Very Good,4.3,212,Mon-Sun
1017,Street Food Co.,250,"Fast Food,Chinese",Virar,Food Truck,6pm to 3am,Very Good,4.1,274,Mon-Sun

In [61]:
#Q5)Which places have the highest rated restaurant for each Cuisine Type in Mumbai?
#Assuming restaurants have a rating above 4.5
highest_rated_df = zomato_df[zomato_df['RATING'] >= 4.5]
highest_rated_df

#Word/Term                       Definition

#highest_rated_df              → New DataFrame to store top-rated restaurants
#zomato_df['RATING']           → Selects the RATING column
#>= 4.5                        → Returns True for rows where rating is
                                 #4.5 or higher, False otherwise
#zomato_df[...]                → Filters and keeps only rows where condition is True
#highest_rated_df              → Displays the filtered DataFrame

#EDA Question Answered:
#Q5 → Which places have the highest-rated restaurant for each
     #Cuisine Type in Mumbai? (Assuming rating above 4.5)

#Filters all restaurants with a rating of 4.5 or above, identifying the highest rated places across different regions and cuisine types in Mumbai.

,NAME,PRICE,CUSINE_CATEGORY,REGION,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES,DAYS_OPEN
0,Hitchki,1200,"Modern Indian,North Indian,Chinese,Momos,Birya...",Bandra,Casual Dining,12noon to 130am,Excellent,4.9,3529,Mon-Sun
6,Persian Darbar,1300,"Biryani,North Indian,Chinese,Mughlai",Marol,Casual Dining,10am to 3am,Excellent,4.5,3058,Mon-Sun
7,Tanatan,1500,Modern Indian,Juhu,Casual Dining,12noon to 130am,Excellent,4.7,1842,Mon-Sun
9,Plum by Bent Chair,1800,Asian,Lower Parel,Casual Dining,12noon to 1am,Excellent,4.7,1876,Mon-Sun
10,Angrezi Dhaba,1500,"North Indian,Chinese,Thai,European",Dadar,Bar,12noon to 1am,Excellent,4.5,2092,Mon-Sun
...,...,...,...,...,...,...,...,...,...,...
14228,Zaika Crave - Club Aquaria,1300,"North Indian,Continental,Chinese,Desserts",Borivali,Casual Dining,"11am to 330pm,7pm to 1130pm",Excellent,4.5,1302,"Mon,Tue,Wed..."
14234,Cone Culture,250,European,Kharghar,Casual Dining,Closed,Excellent,4.6,492,"Mon,12noon to 11pm(Tue-Sun"
15007,Dessertino,300,"Desserts,Ice Cream",Kandivali,Dessert Parlor,11am to 12midnight,Excellent,4.8,184,Mon-Sun
15051,Tick-eat,800,"North Indian,Italian,Chinese,Mexican,Lebanese",Mulund,Casual Dining,"1130am to 330pm,7pm to 1130pm",Excellent,4.5,754,Mon-Sun
15056,Daftar Goregaon,750,"Pizza,Chinese,North Indian,Beverages",Goregaon,Casual Dining,12noon to 1130pm,Excellent,4.6,388,Mon-Sun

In [63]:
fig = px.histogram(highest_rated_df, x='REGION', color='CUSINE TYPE', 
                    title= 'No. of Best Restaurants for each Cuisine Type by Places').update_xaxes(categoryorder="total descending")
fig.show()

#Word/Term                              Definition

#fig                                  → Variable storing the plotly figure object
#px.histogram()                       → Creates a histogram (bar chart of frequencies)
#highest_rated_df                     → DataFrame filtered for ratings >= 4.5
#x='REGION'                           → X-axis shows the REGION column values
#color='CUSINE TYPE'                  → Each cuisine type gets a different colour in bars
#title=                                → Sets chart title as
#'No. of Best Restaurants for each
 #Cuisine Type by Places'
#.update_xaxes()                      → Modifies the appearance of the x-axis
#categoryorder="total descending"     → Sorts x-axis regions by total bar height,
                                        #highest count first to lowest last
#fig.show()                           → Renders and displays the chart

#EDA Question Answered:
#Q5 → Which places have the highest-rated restaurant for each Cuisine Type in Mumbai?

#Creates a stacked histogram showing the count of top-rated (4.5+) restaurants by Region, colour-coded by Cuisine Type, sorted from highest to lowest count for easy comparison.

In [64]:
#Q6)What is the Avg Price Distibution of highest rated restaurant for each Cuisine Type in Mumbai?
highest_rated_price_df = highest_rated_df.groupby(by=['REGION', 'CUSINE TYPE'])['PRICE'].mean().reset_index()
highest_rated_price_df.head()

#Word/Term                              Definition

#highest_rated_price_df               → New DataFrame to store average price
                                        #for each Region & Cuisine Type
#highest_rated_df                     → DataFrame filtered for ratings >= 4.5
#.groupby()                           → Groups rows that share the same values
#by=['REGION', 'CUSINE TYPE']         → Groups data by REGION and CUSINE TYPE
                                        #combination together
#['PRICE']                            → Selects the PRICE column to perform
                                        #calculation on
#.mean()                              → Calculates the average PRICE for
                                        #each group
#.reset_index()                       → Converts the grouped result back into
                                        #a regular DataFrame with default index
#highest_rated_price_df.head()        → Previews first 5 rows of the result

#EDA Question Answered:
#Q6 → What is the Avg Price Distribution of highest rated restaurant for each Cuisine Type in Mumbai?

#Groups top-rated (4.5+) restaurants by Region and Cuisine Type, then calculates the average price for each combination to understand price distribution patterns.

    REGION     CUSINE TYPE   PRICE
0  Andheri             Bar  1600.0
1  Andheri            Café   800.0
2  Andheri   Casual Dining  1175.0
3  Andheri  Dessert Parlor   300.0
4  Andheri          Lounge  1700.0

In [66]:
fig = px.scatter(highest_rated_price_df, x="REGION", y="PRICE", color="CUSINE TYPE", symbol="CUSINE TYPE",
title=' Avg Price Distribution of High-rated restaurants for each Cuisine Type').update_traces(marker_size=10)
fig.show()

#Word/Term                              Definition

#fig                                  → Variable storing the plotly figure object
#px.scatter()                         → Creates a scatter plot
#highest_rated_price_df               → DataFrame with avg price per Region & Cuisine
#x="REGION"                           → X-axis shows the REGION values
#y="PRICE"                            → Y-axis shows the average PRICE values
#color="CUSINE TYPE"                  → Each cuisine type gets a different colour dot
#symbol="CUSINE TYPE"                 → Each cuisine type gets a different marker shape
#title=                                → Sets chart title as
#'Avg Price Distribution of
 #High-rated restaurants for
 #each Cuisine Type'
#.update_traces()                     → Modifies the appearance of plotted markers
#marker_size=10                       → Sets the size of all scatter points to 10
#fig.show()                           → Renders and displays the chart

#EDA Question Answered:
#Q6 → What is the Avg Price Distribution of the highest rated Restaurant for each Cuisine Type in Mumbai?

#Creates a scatter plot showing the average price across Regions, colour and symbol coded by Cuisine Type, to visualize price distribution patterns of top-rated restaurants.

In [67]:
#Q7)Which areas have a large number of Chinese Restaurant Market?
chinese_df = zomato_df[zomato_df['CUSINE_CATEGORY'].str.contains('Chinese')]
chinese_df

#Word/Term                            Definition

#chinese_df                         → New DataFrame to store Chinese restaurants
#zomato_df['CUSINE_CATEGORY']       → Selects the CUSINE_CATEGORY column
#.str                                → Accessor to apply string methods
#.contains('Chinese')                → Returns True for rows where the text
                                       #contains "Chinese", False otherwise
#zomato_df[...]                     → Filters and keeps only Chinese restaurant rows
#chinese_df                          → Displays the filtered DataFrame

#EDA Question Answered:
#Q7 → Which areas have a large number of Chinese Restaurant Market?

#Filters all restaurants that serve Chinese cuisine, creating a dataset ready to be grouped by REGION to identify areas with the highest Chinese restaurant count.

,NAME,PRICE,CUSINE_CATEGORY,REGION,CUSINE TYPE,TIMING,RATING_TYPE,RATING,VOTES,DAYS_OPEN
0,Hitchki,1200,"Modern Indian,North Indian,Chinese,Momos,Birya...",Bandra,Casual Dining,12noon to 130am,Excellent,4.9,3529,Mon-Sun
2,Chin Chin Chu,1800,"Asian,Chinese",Juhu,Casual Dining,12noon to 1am,Very Good,4.2,337,Mon-Sun
4,BKC DIVE,1200,"North Indian,Chinese,Continental",Bandra,Bar,1130am to 1am,Veľmi dobré,4.4,5995,Mon-Sun
5,Flea Bazaar Café,800,"American,Asian,Street Food,North Indian,Luckno...",Lower Parel,Café,12noon to 1am,Very Good,4.2,2042,Mon-Sun
6,Persian Darbar,1300,"Biryani,North Indian,Chinese,Mughlai",Marol,Casual Dining,10am to 3am,Excellent,4.5,3058,Mon-Sun
...,...,...,...,...,...,...,...,...,...,...
15071,Lucknow Zaika,500,"North Indian,Chinese",Kurla,Quick Bites,12noon to 2am,Average,2.6,36,Mon-Sun
15072,Zuha's Kitchen,400,"Chinese,North Indian,Mughlai",Mumbai Central,Quick Bites,"12noon to 4pm,730pm to 430am",Average,3.3,13,Mon-Sun
15075,Tirupati Balaji,500,"Chinese,Fast Food,North Indian",Andheri,Casual Dining,"8am to 11pm,12midnight to 115am",Good,3.5,267,Mon-Sun
15076,Hari Om Snack Bar,350,"Fast Food,South Indian,Chinese",Kandivali,Quick Bites,11am to 230am,Good,3.7,64,Mon-Sun
15079,Mandarin Panda,400,"Desserts,Chinese,Thai",Malad,none,"12noon to 330pm,7pm to 1am",Good,3.7,121,Mon-Sun

In [70]:
chinese_rest_df = chinese_df.groupby(by='REGION').agg({'NAME':'count', 'PRICE':'mean'}).rename(columns={'NAME':'COUNT OF RESTAURANTS'})
chinese_rest_df = chinese_rest_df.reset_index() 
chinese_rest_df = chinese_rest_df.sort_values('COUNT OF RESTAURANTS', ascending=False).head(25)
chinese_rest_df.head()

#Word/Term                              Definition

#chinese_rest_df                      → New DataFrame storing Chinese restaurant
                                        #stats grouped by region
#chinese_df                           → DataFrame filtered for Chinese cuisine
#.groupby(by='REGION')                → Groups all rows by REGION value
#.agg({...})                          → Applies different aggregation per column
#'NAME':'count'                       → Counts the number of restaurant names per region
#'PRICE':'mean'                       → Calculates average price per region
#.rename(columns={...})               → Renames 'NAME' column to
                                        #'COUNT OF RESTAURANTS'
#.reset_index()                       → Converts REGION from index back into a
                                        #normal column so px.bar() can use it as x-axis
#.sort_values()                       → Sorts the DataFrame by a specified column
#'COUNT OF RESTAURANTS'               → Sort key — number of Chinese restaurants
#ascending=False                      → Sorts highest count first
#.head(25)                            → Keeps only top 25 regions
#chinese_rest_df.head()               → Previews first 5 rows of final result

#EDA Question Answered:
#Q7 → Which areas have a large number of Chinese Restaurant Markets?

#Groups Chinese restaurants by Region, counts total restaurants and average price per region, then sorts to show areas with the largest Chinese restaurant market — Andheri leads with 389.

       REGION  COUNT OF RESTAURANTS       PRICE
71      Thane                   371  590.983827
3     Andheri                   313  627.316294
51  Mira Road                   224  553.348214
45      Malad                   186  604.032258
27   Goregaon                   163  548.773006

In [72]:
fig = px.bar(chinese_rest_df, x='REGION', y='COUNT OF RESTAURANTS', color='PRICE', title='No. of Chinese Restaurant by Places')
fig.show()

#Word/Term                              Definition

#fig                                  → Variable storing the plotly figure object
#px.bar()                             → Creates a bar chart
#Chinese_rest_df                      → DataFrame with Chinese restaurant counts
                                        #and the average price per region
#x='REGION'                           → X-axis shows the REGION column values
#y='COUNT OF RESTAURANTS'             → Y-axis shows the count of Chinese
                                        #restaurants per region
#color='PRICE'                        → Bar colour intensity based on average price
#title=                                → Sets chart title as
#'No. of Chinese Restaurants
 #by Places'
#fig.show()                           → Renders and displays the chart

#EDA Question Answered:
#Q7 → Which areas have a large number of Chinese restaurant markets?

#Creates a bar chart showing the count of Chinese restaurants by region, with bar colour indicating average price, highlighting Andheri as the area with the largest market.

In [74]:
#Q8)Is there a relation between Price and Rating by each Cuisine Type?
price_rating_df = zomato_df.groupby(['CUSINE TYPE', 'RATING'])['PRICE'].mean().reset_index()
price_rating_df

#Word/Term                              Definition

#price_rating_df                      → New DataFrame storing avg price
                                        #per Cuisine Type & Rating combo
#zomato_df                            → The cleaned Zomato Mumbai DataFrame
#.groupby()                           → Groups rows that share the same values
#['CUSINE TYPE', 'RATING']            → Groups data by CUSINE TYPE and
                                        #RATING combination together
#['PRICE']                            → Selects the PRICE column to perform
                                        #calculation on
#.mean()                              → Calculates the average PRICE for
                                        #each group
#.reset_index()                       → Converts the grouped result back into
                                        #a regular DataFrame with default index
#price_rating_df                      → Displays the final DataFrame

#EDA Question Answered:
#Q8 → Is there a relation between Price and Rating by each Cuisine Type?

#Groups restaurants by Cuisine Type and Rating, then calculates the average price for each combination to explore whether Higher-rated restaurants tend to have higher prices.

    CUSINE TYPE  RATING       PRICE
0        Bakery     2.7  400.000000
1        Bakery     2.8  285.714286
2        Bakery     2.9  328.571429
3        Bakery     3.0  300.000000
4        Bakery     3.1  369.117647
..          ...     ...         ...
278        none     4.3  683.333333
279        none     4.4  555.000000
280        none     4.5  420.000000
281        none     4.6  687.500000
282        none     4.7  350.000000

[283 rows x 3 columns]

In [75]:
fig = px.line(price_rating_df, y="PRICE", x="RATING",color='CUSINE TYPE')
fig.show()

#Word/Term                  Definition

#fig                       → Variable storing the plotly figure object
#px.line()                 → Creates a line chart
#price_rating_df           → DataFrame with avg price per Cuisine Type & Rating
#y = "PRICE"                 → Y-axis shows the average PRICE values
#x="RATING"                → X-axis shows the RATING values
#color='CUSINE TYPE'       → Each cuisine type gets its own colored line
#fig.show()                → Renders and displays the chart

#EDA Question Answered:
#Q8 → Is there a relation between Price and Rating by each Cuisine Type?

#Creates a line chart showing how the average price changes across different rating values, with a separate line per Cuisine Type to visualize price-rating trends.

In [76]:
#Q9)Is there a relation between Region and Price?
region_price_df = zomato_df.groupby(['REGION'])['PRICE'].mean().reset_index()
region_price_df

#Word/Term                              Definition

#region_price_df                      → New DataFrame storing avg price per Region
#zomato_df                            → The cleaned Zomato Mumbai DataFrame
#.groupby()                           → Groups rows that share the same values
#['REGION']                           → Groups data by REGION value
#['PRICE']                            → Selects the PRICE column to perform
                                        #calculation on
#.mean()                              → Calculates the average PRICE for
                                        #each region
#.reset_index()                       → Converts the grouped result back into
                                        #a regular DataFrame with default index
#region_price_df                      → Displays the final DataFrame

#EDA Question Answered:
#Q9 → Is there a relation between Region and Price?

#Groups all restaurants by Region and calculates the average price for each, helping identify which areas in Mumbai have higher or lower average dining costs.

        REGION       PRICE
0       Airoli  452.287582
1      Alibaug  665.000000
2    Ambernath  514.000000
3      Andheri  562.506596
4       Bandra  724.945946
..         ...         ...
75    Vikhroli  480.434783
76  Vile Parle  464.457831
77       Virar  452.027027
78      Wadala  427.500000
79       Worli  537.012987

[80 rows x 2 columns]

In [77]:
fig = px.scatter(region_price_df, x="REGION", y="PRICE").update_traces(marker_size=8)
fig.show()

#Word/Term                  Definition

#fig                       → Variable storing the plotly figure object
#px.scatter()              → Creates a scatter plot
#region_price_df           → DataFrame with average price per Region
#x="REGION"                → X-axis shows the REGION values
#y="PRICE"                 → Y-axis shows the average PRICE values
#.update_traces()          → Modifies the appearance of plotted markers
#marker_size=8             → Sets the size of all scatter points to 8
#fig.show()                → Renders and displays the chart

#EDA Question Answered:
#Q9 → Is there a relation between Region and Price?

#Creates a scatter plot showing average price for each Region in Mumbai, helping visualize which areas have higher or lower dining costs at a glance.

In [ ]:
#Q10)Find the list of Affordable Restaurants?

The criteria for Affordable Restaurants would be:-
1) Low Price 2) High Rated
First step will be to find the restaurants with average cost 1/4th the average cost of most expensive restaurant in our dataframe.
Let me explain:-The most expensive restaurant has an average meal cost= 6000. We'll try to stay economical and only pick the
restaurants that are 1/4th of 6000

In [78]:
max_price = zomato_df['PRICE'].max()
one_fourth_price = max_price/4
one_fourth_price

#Word/Term                  Definition

#max_price                → Variable storing the highest price value
#zomato_df['PRICE']       → Selects the PRICE column from zomato_df
#.max()                   → Returns the maximum (highest) value in PRICE
#one_fourth_price          → Variable storing 1/4th of the max price
#max_price / 4              → Divides max_price by 4
#one_fourth_price          → Displays the calculated one-fourth value

#Calculates the maximum restaurant price and finds its one-fourth (1/4th) value, used as a threshold to identify expensive restaurants that are 1/4th of the max price.

1250.0

In [79]:
#Finding list of restaurants that have price less than and equal to 1/4th of the max price i.e Finding Cheap Restaurant
aff_rest_df = zomato_df[['NAME', 'PRICE', 'CUSINE_CATEGORY', 'REGION', 'CUSINE TYPE']]
aff_rest_df = aff_rest_df[aff_rest_df['PRICE'] <= 1250]
aff_rest_df.sort_values(by='PRICE', inplace=True)
aff_rest_df

#Word/Term                              Definition

#aff_rest_df                          → New DataFrame to store affordable
                                        #(cheap) restaurants
#zomato_df[[...]]                     → Selects only specific columns:
#['NAME', 'PRICE',                      NAME, PRICE, CUSINE_CATEGORY,
# 'CUSINE_CATEGORY', 'REGION',          REGION, CUSINE TYPE
# 'CUSINE TYPE']
#aff_rest_df['PRICE'] <= 1250         → Filters rows where PRICE is less than
                                        #or equal to 1250 (1/4th of max price)
#aff_rest_df[...]                     → Keeps only affordable restaurant rows
#.sort_values()                       → Sorts the DataFrame by a specified column
#by='PRICE'                           → Sorts based on the PRICE column
#inplace=True                         → Permanently modifies aff_rest_df
                                        #without reassignment
#aff_rest_df                          → Displays the final sorted DataFrame

#Filters and sorts restaurants priced at or below 1250 (1/4th of the max price), identifying affordable/cheap restaurant options across Mumbai.

,NAME,PRICE,CUSINE_CATEGORY,REGION,CUSINE TYPE
6137,Sanjog Wine N Dine,5,"North Indian,Chinese",Thane,Casual Dining
2925,Jab We Eat,50,"South Indian,North Indian,Maharashtrian,Fast Food",Girgaum,none
9598,Ho5 Store,50,Fast Food,Matunga,none
9589,Golden Butterfly,100,"Bakery,Desserts",Mira Road,Bakery
5916,Madhuri Puranpoli,100,Maharashtrian,Vile Parle,none
...,...,...,...,...,...
2740,Peninsula Next,1200,"North Indian,Mughlai,Chinese",Sion,Casual Dining
5528,The Thekka,1200,"Finger Food,Continental,North Indian,Chinese",Vashi,Lounge
964,Bijoli Grill,1250,Bengali,Powai,Casual Dining
6045,Fabelle at The Chocolate Boutique - ITC Grand ...,1250,Desserts,Parel,Dessert Parlor
7301,SamBar Pub & Kitchen,1250,"Finger Food,South Indian,North Indian",Khar,Pub

In [80]:
#Finding the highest rated list of restaurants
highrate_rest_df = zomato_df[['NAME', 'PRICE', 'CUSINE_CATEGORY', 'REGION', 'CUSINE TYPE','RATING']]
highrate_rest_df = highrate_rest_df[highrate_rest_df['RATING'] >= 4.5]
highrate_rest_df.sort_values(by='PRICE', inplace=True)
highrate_rest_df

#Word/Term                              Definition

#highrate_rest_df                     → New DataFrame to store highest
                                        #rated restaurants
#zomato_df[[...]]                     → Selects only specific columns:
#['NAME', 'PRICE',                      NAME, PRICE, CUSINE_CATEGORY,
# 'CUSINE_CATEGORY', 'REGION',          REGION, CUSINE TYPE, RATING
# 'CUSINE TYPE', 'RATING']
#highrate_rest_df['RATING'] >= 4.5    → Filters rows where RATING is
                                        #4.5 or higher
#highrate_rest_df[...]                → Keeps only highest rated restaurant rows
#.sort_values()                       → Sorts the DataFrame by a specified column
#by='PRICE'                           → Sorts based on the PRICE column
#inplace=True                         → Permanently modifies highrate_rest_df
                                        #without reassignment
#highrate_rest_df                     → Displays the final sorted DataFrame

#Filters and sorts restaurants with a rating of 4.5 or above, creating a list of the highest rated restaurants in Mumbai ordered by price.

,NAME,PRICE,CUSINE_CATEGORY,REGION,CUSINE TYPE,RATING
1502,Cake Centre-The Dessert Maker,150,Desserts,Mohammad Ali Road,Dessert Parlor,4.6
763,Curry And Combos Twist,200,"North Indian,Chinese",Andheri,Quick Bites,4.5
807,Moussestruck,200,Desserts,Andheri,none,4.5
14234,Cone Culture,250,European,Kharghar,Casual Dining,4.6
725,Belo Pops,300,"Ice Cream,Desserts,Beverages",Andheri,none,4.5
...,...,...,...,...,...,...
5335,Mia Cucina,2000,Italian,Bandra,Casual Dining,4.5
1786,Global Fusion,2000,"Chinese,Japanese,Asian,North Indian",Worli,Fine Dining,4.6
8887,Drifters Tap Station,2000,"North Indian,Continental,European,American",Bandra,Casual Dining,4.5
12625,House of Mandarin,2100,"Chinese,Sushi,Asian",Bandra,Casual Dining,4.5
902,The Harbour Bay - SeaFood Kitchen & Bar,2400,"Seafood,Beverages",Bandra,Casual Dining,4.5

Now, we'll merge the aff_rest_df with highrate_rest_df to obtain the intersection i.e the list of Affordable Restaurants !!

In [81]:
highrate_aff_df = pd.merge(aff_rest_df, highrate_rest_df, how='inner', on=['NAME', 'REGION'])
highrate_aff_df = highrate_aff_df[['NAME', 'PRICE_x', 'CUSINE_CATEGORY_x', 'REGION', 'CUSINE TYPE_x']]
highrate_aff_df.rename(columns={'NAME':'NAME', 'PRICE_x':'PRICE', 'CUSINE_CATEGORY_x':'CUSINE_CATEGORY',
'REGION':'REGION', 'CUSINE TYPE_x':'CUSINE TYPE'},inplace=True)

#Word/Term                              Definition

#highrate_aff_df                      → New DataFrame storing restaurants that
                                        #are BOTH affordable AND highest rated
#pd.merge()                           → Combines two DataFrames based on
                                        #matching column values
#aff_rest_df                          → Affordable restaurants DataFrame
#highrate_rest_df                     → Highest rated restaurants DataFrame
#how='inner'                          → Keeps only rows that match in BOTH
                                        #DataFrames (intersection)
#on=['NAME', 'REGION']                → Matches rows where NAME and REGION
                                        #are the same in both DataFrames

#highrate_aff_df[[...]]               → Selects specific columns after merge
#'PRICE_x', 'CUSINE_CATEGORY_x',      → "_x" suffix added automatically since
#'CUSINE TYPE_x'                        these columns existed in both DataFrames
                                        #(keeping the version from aff_rest_df)

#.rename(columns={...})               → Renames the "_x" suffixed columns back
                                        #to their original clean names
#inplace=True                         → Permanently modifies highrate_aff_df

#Merges affordable restaurants with highest rated restaurants to find the best of both — restaurants that are cheap (≤1250 price) AND highly rated (≥4.5 rating).

In [82]:
#Affordable Restaurants with low price and high rating
highrate_aff_df

#Word/Term            Definition

#highrate_aff_df     → Final merged DataFrame containing restaurants
                       #that are BOTH affordable AND highest rated

#EDA Question Answered:
#Q10 → Affordable Restaurants with low price and high rating

#Displays the final list of "best value" restaurants in Mumbai — ones that are cheap (price ≤ 1250) AND highly rated (≥ 4.5), ideal recommendations for budget-conscious, quality-seeking diners.

,NAME,PRICE,CUSINE_CATEGORY,REGION,CUSINE TYPE
0,Cake Centre-The Dessert Maker,150,Desserts,Mohammad Ali Road,Dessert Parlor
1,Curry And Combos Twist,200,"North Indian,Chinese",Andheri,Quick Bites
2,Moussestruck,200,Desserts,Andheri,none
3,Cone Culture,250,European,Kharghar,Casual Dining
4,Smiley Pops,300,"Desserts,Ice Cream,Beverages,Sandwich",Andheri,Dessert Parlor
...,...,...,...,...,...
60,Wild Dining Restaurant,1200,"North Indian,Continental,Mexican,Chinese",Andheri,Casual Dining
61,Invento,1200,"Chinese,Fast Food,North Indian,Italian,Mexican",Lower Parel,Casual Dining
62,Culinary Tales,1200,"Chinese,European,Continental,Salad,Italian,Pizza",Andheri,Casual Dining
63,Hitchki,1200,"Modern Indian,North Indian,Chinese,Momos,Birya...",Bandra,Casual Dining
64,The Joker Bistro,1200,"North Indian,Chinese,Continental",CBD Belapur,Casual Dining

Q10) Find the list of most Reliable Restaurants?
The criteria for most Reliable Restaurants would be:-
1) Low Price 2) High Rated 3) Large No. of Votes
First step will be to find the restaurants with Votes greater than Mean of Votes

In [83]:
mean_votes = zomato_df['VOTES'].mean()
mean_votes

#Word/Term              Definition

#mean_votes           → Variable storing the average number of votes
#zomato_df['VOTES']   → Selects the VOTES column from zomato_df
#.mean()               → Calculates the average (mean) value of VOTES
#mean_votes            → Displays the calculated average votes value

#Calculates the average number of votes across all restaurants, used as a threshold to identify restaurants with votes greater than the mean (popular restaurants).

np.float64(177.2656679624538)

In [84]:
#Finding list of restaurants that have Votes greater than and equal to Mean of Vote
mean_rest_df = zomato_df[['NAME', 'PRICE', 'CUSINE_CATEGORY', 'REGION', 'CUSINE TYPE', 'VOTES']]
mean_rest_df = mean_rest_df[mean_rest_df['VOTES'] > 177]
mean_rest_df.sort_values(by='VOTES', inplace=True)
mean_rest_df

#Word/Term                              Definition

#mean_rest_df                         → New DataFrame storing restaurants
                                        #with above-average votes
#zomato_df[[...]]                     → Selects only specific columns:
#['NAME', 'PRICE',                      NAME, PRICE, CUSINE_CATEGORY,
# 'CUSINE_CATEGORY', 'REGION',          REGION, CUSINE TYPE, VOTES
# 'CUSINE TYPE', 'VOTES']
#mean_rest_df['VOTES'] > 177          → Filters rows where VOTES is
                                        #greater than 177 (mean value)
#mean_rest_df[...]                    → Keeps only popular restaurant rows
#.sort_values()                       → Sorts the DataFrame by a specified column
#by='VOTES'                           → Sorts based on the VOTES column
#inplace=True                         → Permanently modifies mean_rest_df
                                        #without reassignment
#mean_rest_df                         → Displays the final sorted DataFrame

#Filters and sorts restaurants with votes greater than the mean (177), identifying the most popular/well-known restaurants in Mumbai based on customer engagement.

,NAME,PRICE,CUSINE_CATEGORY,REGION,CUSINE TYPE,VOTES
4194,Sai Sagar Veg Treat,500,"North Indian,South Indian,Chinese,Fast Food,Be...",Kalyan,Casual Dining,178
884,Rajmanya- Seafood family restaurant,800,"Maharashtrian,Konkan,Seafood",Vashi,Casual Dining,178
3914,Ice Cafe,500,"Fast Food,Ice Cream,Beverages,Pizza",Borivali,Quick Bites,178
7897,Konkan Lajjatdar,500,"Seafood,Biryani,Beverages,Chinese,Malwani,Konkan",Andheri,Casual Dining,178
3828,Frozen Delight -The Dessert Cafe,250,"Desserts,Ice Cream",Airoli,Dessert Parlor,178
...,...,...,...,...,...,...
8539,Leopold Cafe & Bar,1600,"American,Chinese,Mughlai,Italian",Colaba,Casual Dining,7327
1251,Joey's Pizza,800,Pizza,Malad,Quick Bites,7350
5337,Chili's American Grill & Bar,1400,"American,Mexican,Burger,Tex-Mex",Powai,Casual Dining,7377
3751,Prithvi Cafe,700,"Cafe,Fast Food",Juhu,Café,8000
8897,Candies,700,"Cafe,Italian,North Indian,Desserts",Bandra,Café,10217

These are the most reliable, highest-rated and affordable restaurants:-

We obtain this dataframe by simply taking the intersection of highrate_aff_df & mean_rest_df

This dataframe, obtained below, shows the restaurants whose:

1. Cost is below 1250
2. Rating is above 4.5
3. Votes are above 177

In [85]:
reliable_rest_df = pd.merge(mean_rest_df, highrate_aff_df, how='inner', on=['NAME', 'REGION'])
reliable_rest_df = reliable_rest_df[['NAME', 'PRICE_x', 'CUSINE_CATEGORY_x', 'REGION', 'CUSINE TYPE_x']]
reliable_rest_df.rename(columns={'NAME':'NAME', 'PRICE_x':'PRICE', 'CUSINE_CATEGORY_x':'CUSINE_CATEGORY',
'REGION':'REGION', 'CUSINE TYPE_x':'CUSINE TYPE'},inplace=True)

#Word/Term                              Definition

#reliable_rest_df                     → New DataFrame storing restaurants that
                                        #are popular AND affordable+high rated
#pd.merge()                           → Combines two DataFrames based on
                                        #matching column values
#mean_rest_df                         → Restaurants with votes > mean (popular)
#highrate_aff_df                      → Affordable AND highest rated restaurants
#how='inner'                          → Keeps only rows that match in BOTH
                                        #DataFrames (intersection)
#on=['NAME', 'REGION']                → Matches rows where NAME and REGION
                                        #are the same in both DataFrames

#reliable_rest_df[[...]]              → Selects specific columns after merge
#'PRICE_x', 'CUSINE_CATEGORY_x',      → "_x" suffix added automatically since
#'CUSINE TYPE_x'                        these columns existed in both DataFrames
                                        #(keeping the version from mean_rest_df)

#.rename(columns={...})               → Renames the "_x" suffixed columns back
                                        #to their original clean names
#inplace=True                         → Permanently modifies reliable_rest_df

#Merges popular restaurants (votes > mean) with affordable high-rated restaurants to find the most "reliable" options — restaurants that are cheap, highly rated, AND well-voted by customers.

In [86]:
reliable_rest_df

#Word/Term            Definition

#reliable_rest_df    → Final merged DataFrame containing restaurants
                       #that are popular, affordable, and highly rated

#Displays the final list of "most reliable" restaurants in Mumbai — cheap ones (≤1250 price), highly rated (≥4.5), AND popular (votes > mean), making them the best overall recommendations.

,NAME,PRICE,CUSINE_CATEGORY,REGION,CUSINE TYPE
0,Rajmanya- Seafood family restaurant,800,"Maharashtrian,Konkan,Seafood",Vashi,Casual Dining
1,Fresh Food Co.,500,"Continental,Healthy Food,Salad,Beverages,Desse...",Santacruz,none
2,Dessertino,300,"Desserts,Ice Cream",Kandivali,Dessert Parlor
3,Invento,1200,"Chinese,Fast Food,North Indian,Italian,Mexican",Lower Parel,Casual Dining
4,Maharashtra Lunch Home,600,"Maharashtrian,Malwani,Konkan,Seafood",Kharghar,Casual Dining
5,Regano's,600,"Continental,Fast Food,Italian,Desserts",Malad,Casual Dining
6,Big Bang Cuurry,350,"North Indian,Biryani,Rolls",Andheri,none
7,Sandy's Den,1000,"Fast Food,Bar Food",Chembur,Casual Dining
8,Angrezi Patiyalaa,1200,"North Indian,Finger Food,American,Mexican,Chinese",Andheri,Casual Dining
9,Maezo,1000,Modern Indian,Thane,Casual Dining
10,Tossin Pizza,900,"Pizza,Italian,Fast Food",Chembur,Casual Dining
11,Little West Pizza,600,Pizza,Borivali,Quick Bites
12,Ceremonial Kitchen & Co,1000,"Seafood,Maharashtrian,North Indian,Chinese",Thane,Casual Dining
13,Moussestruck,200,Desserts,Andheri,none
14,Daftar Goregaon,750,"Pizza,Chinese,North Indian,Beverages",Goregaon,Casual Dining
15,Poetry By Love & Cheesecake,1000,"Cafe,Desserts",Juhu,Café
16,Makhan Singh,800,"North Indian,Chinese,Biryani",Powai,none
17,The Joker Bistro,1200,"North Indian,Chinese,Continental",CBD Belapur,Casual Dining
18,Cone Culture,250,European,Kharghar,Casual Dining
19,Peco Peco,700,"Chinese,Seafood,Asian",Powai,none
20,Shuruwat- Veg Food Journey,600,"Continental,Tea,South Indian,Fast Food,Pizza,N...",Ghatkopar,Casual Dining
21,Justice Cafe and Dine,800,"Cafe,Chinese,Italian,Continental,North Indian,...",Thane,Café
22,Thangabali,1000,"Seafood,South Indian,Mangalorean,Andhra,Kerala",Khar,Bar
23,Harsh's Bistro,800,"Chinese,Continental",Malad,Casual Dining
24,Quarter Canteen,1100,"North Indian,Seafood,Chinese",Bandra,Casual Dining
25,Culinary Tales,1200,"Chinese,European,Continental,Salad,Italian,Pizza",Andheri,Casual Dining
26,Dum & Curry,700,"Mughlai,North Indian,Chinese",Powai,Quick Bites
27,Curry Culture,800,"North Indian,Biryani,Chinese,Kebab,Mughlai,Asian",Powai,none
28,Belo Pops,300,"Ice Cream,Desserts,Beverages",Andheri,none
29,Tick-eat,800,"North Indian,Italian,Chinese,Mexican,Lebanese",Mulund,Casual Dining
30,Coppetto Artisan Gelato,350,"Ice Cream,Desserts",Bandra,Dessert Parlor
31,Zaika Restaurant & Party Hall,1000,"North Indian,Chinese,Beverages",Bhayandar,Casual Dining
32,Shaollin Temple,1000,"Chinese,Thai",CBD Belapur,Casual Dining
33,Spice Republic,1200,"Cafe,Continental,Mediterranean,Mexican,Italian...",Borivali,Café
34,Aquafire Restaurant,1100,"North Indian,Continental,Chinese,Italian",Vile Parle,Casual Dining
35,Rajdhani,950,"Gujarati,Rajasthani,North Indian",Ghatkopar,Casual Dining
36,Wild Dining Restaurant,1200,"North Indian,Continental,Mexican,Chinese",Andheri,Casual Dining
37,Family Tree,800,"Italian,Mexican,North Indian,Chinese,Salad",Thane,Casual Dining
38,Bombay Salad Co.,900,"Salad,Healthy Food,Juices",Bandra,Casual Dining
39,Cafe Monza,1000,"Italian,American,Salad,Mexican",Kharghar,Casual Dining
40,Hitchki,1200,"Modern Indian,North Indian,Chinese,Momos,Birya...",Bandra,Casual Dining
41,Vedge,1000,"Thai,Chinese,North Indian,Mexican,Italian,Asian",Andheri,Casual Dining
42,Joey's Pizza,800,Pizza,Malad,Quick Bites